DROP TABLE USERS(
	USER_ID 				INTEGER PRIMARY KEY,
	FIRST_NAME 			VARCHAR2(100),
	LAST_NAME  			VARCHAR2(100),
	YEAR_OF_BIRTH 	INTEGER,
	MONTH_OF_BIRTH	INTEGER,
	DAY_OF_BIRTH		INTEGER,
	GENDER					VARCHAR2(100)
);

DROP TABLE FRIENDS(
	USER1_ID			INTEGER NOT NULL,
	USER2_ID			INTEGER NOT NULL,
	
	FOREIGN KEY (USER1_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (USER2_ID) REFERENCES USERS(USER_ID)
);

DROP TABLE CITIES(
	CITY_ID				INTEGER PRIMARY KEY,
	CITY_NAME			VARCHAR2(100),
	STATE_NAME		VARCHAR2(100),
	COUNTRY_NAME 	VARCHAR2(100)
);

DROP TABLE USER_CURRENT_CITY(
	USER_ID						INTEGER NOT NULL,
	CURRENT_CITY_ID		INTEGER NOT NULL,

	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITIES(CITY_ID)
);


DROP TABLE USER_HOMETOWN_CITY(
	USER_ID						INTEGER NOT NULL,
	CURRENT_CITY_ID		INTEGER NOT NULL,

	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITIES(CITY_ID)
);

DROP TABLE MESSAGE(
	MESSAGE_ID 				INTEGER PRIMARY KEY,
	SENDER_ID					INTEGER NOT NULL,
	RECEIVER_ID				INTEGER NOT NULL,
	MESSAGE_CONTENT		VARCHAR2(2000),
	SENT_TIME					TIMESTAMP,

	FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (RECIEVER_ID) REFERENCES USERS(USER_ID)
);

DROP TABLE PROGRAMS(
	PROGRAM_ID				INTEGER PRIMARY KEY,
	INSTITUTION				VARCHAR2(100),
	CONCENTRATION			VARCHAR2(100),
	DEGREE						VARCHAR2(100)
);

DROP TABLE EDUCATION(
	USER_ID					INTEGER NOT NULL,
	PROGRAM_ID			INTEGER NOT NULL,
	PROGRAM_YEAR		INTEGER,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAMS(PROGRAM_ID)
);

DROP TABLE USER_EVENTS(
	EVENT_ID						INTEGER PRIMARY KEY,
	EVENT_CREATOR_ID		INTEGER,
	EVENT_NAME					VARCHAR2(100),
	EVENT_TAGLINE				VARCHAR2(100),
	EVENT_DESCRIPTION		VARCHAR2(100),
	EVENT_HOST					VARCHAR2(100),
	EVENT_TYPE					VARCHAR2(100),
	EVENT_SUBTYPE				VARCHAR2(100),
	EVENT_LOCATION			VARCHAR2(100),
	EVENT_CITY_ID				INTEGER,
	EVENT_START_TIME		TIMESTAMP,
	EVENT_END_TIME			TIMESTAMP,

	FOREIGN KEY (EVENT_CREATOR_ID) REFERENCES USERS(USER_ID),
	FOREIGN KEY (EVENT_CITY_ID) REFERENCES CITIES(CITY_ID)
);

DROP TABLE PARTICIPANTS(
	EVENT_ID			INTEGER,
	USER_ID				INTEGER,
	CONFIRMATION	VARCHAR2(100),

	FOREIGN KEY (EVENT_ID) REFERENCES USER_EVENT(EVENT_ID),
	FOREIGN KEY (USER_ID)  REFERENCES USERS(USER_ID)
);

DROP TABLE ALBUMS(
	ALBUM_ID					VARCHAR2(100) PRIMARY KEY,
	ALBUM_OWNER_ID		INTEGER,
	ALBUM_NAME				VARCHAR2(100),
	ALBUM_DROPD_TIME 	TIMESTAMP,
	ALBUM_MODIFIED_TIME TIMESTAMP,
	ALBUM_LINK					VARCHAR2(2000),
	ALBUM_VISIBILITY		VARCHAR2(100),
	COVER_PHOTO_ID			VARCHAR2(100)
);

DROP TABLE PHOTOS(
	PHOTO_ID				VARCHAR2(100) PRIMARY KEY,
	ALBUM_ID				VARCHAR2(100),
	PHOTO_CAPTION		VARCHAR2(2000),
	PHOTO_DROPD_TIME TIMESTAMP,
	PHOTO_MODIFIED_TIME TIMESTAMP,
	PHOTO_LINK			VARCHAR2(2000)
);

DROP TABLE TAGS(
	TAG_PHOTO_ID				VARCHAR2(100),
	TAG_SUBJECT_ID 			INTEGER,
	TAG_DROPD_TIME		TIMESTAMP,
	TAG_X								INTEGER,
	TAG_Y								INTEGER,

	FOREIGN KEY (TAG_PHOTO_ID) 		REFERENCES PHOTOS(PHOTO_ID),
	FOREIGN KEY (TAG_SUBJECT_ID)	REFERENCES USERS(USER_ID)
);
